language: python
python:
  - "3.4"
# command to install dependencies
install: "pip install -r serial-implementation/requirements.txt"
before_script:
 - "chmod +x serial-implementation/run-tests.sh"
# command to run tests
script:
  - "cd serial-implementation"
  - "./run-tests.sh"
  - "cd .."
